import 'package:flutter/material.dart';
import 'package:flutter_story_presenter/src/models/transformable_item.dart';

/// README: THIS FILE WAS GENERATED BY THE GITHUB COPILOT (it is working, but for future reference, it is good to know)

class TransformableContainer extends StatefulWidget {
  final List<TransformableItem> items;
  final bool allowRotation;
  final bool allowScaling;
  final bool allowTranslation;
  final double minScale;
  final double maxScale;
  final Function(String itemId, double scale, double rotation,
      Offset relativeOffset, Offset absoluteOffset)? onItemTransformUpdated;
  final Function(ScaleEndDetails details)? onTransformEnd;
  final Size containerSize;

  const TransformableContainer({
    super.key,
    required this.items,
    required this.containerSize,
    this.allowRotation = true,
    this.allowScaling = true,
    this.allowTranslation = true,
    this.minScale = 0.5,
    this.maxScale = 3.0,
    this.onItemTransformUpdated,
    this.onTransformEnd,
  });

  @override
  State<TransformableContainer> createState() => _TransformableContainerState();
}

class _TransformableContainerState extends State<TransformableContainer>
    with TickerProviderStateMixin {
  String? _activeItemId;
  final Map<String, AnimationController> _animControllers = {};
  final Map<String, Animation<double>> _scaleAnimations = {};
  final Map<String, Animation<double>> _rotationAnimations = {};
  final Map<String, Animation<Offset>> _offsetAnimations = {};

  // Store the initial values at the start of a gesture
  double _baseScale = 1.0;
  double _baseRotation = 0.0;
  // Offset _focalPointStart = Offset.zero;

  // Track the item being manipulated with a single finger
  String? _singleFingerItemId;
  Offset _lastSingleFingerPosition = Offset.zero;

  @override
  void initState() {
    super.initState();
    _initializeAnimations();
  }

  @override
  void didUpdateWidget(TransformableContainer oldWidget) {
    super.didUpdateWidget(oldWidget);

    // Handle items that were added or removed
    _updateAnimationControllers();
  }

  // Convert relative offset (0.0-1.0) to absolute position in the container
  Offset _relativeToAbsoluteOffset(Offset relativeOffset) {
    return Offset(
      relativeOffset.dx * widget.containerSize.width,
      relativeOffset.dy * widget.containerSize.height,
    );
  }

  // Convert absolute position in container to relative offset (0.0-1.0)
  // Offset _absoluteToRelativeOffset(Offset absoluteOffset) {
  //   return Offset(
  //     absoluteOffset.dx / widget.containerSize.width,
  //     absoluteOffset.dy / widget.containerSize.height,
  //   );
  // }

  void _initializeAnimations() {
    for (final item in widget.items) {
      _createAnimationController(item.id);
    }
  }

  void _updateAnimationControllers() {
    // Remove controllers for items that no longer exist
    final currentIds = widget.items.map((item) => item.id).toSet();
    final controllersToRemove =
        _animControllers.keys.where((id) => !currentIds.contains(id)).toList();

    for (final id in controllersToRemove) {
      _animControllers[id]?.dispose();
      _animControllers.remove(id);
      _scaleAnimations.remove(id);
      _rotationAnimations.remove(id);
      _offsetAnimations.remove(id);
    }

    // Add controllers for new items
    for (final item in widget.items) {
      if (!_animControllers.containsKey(item.id)) {
        _createAnimationController(item.id);
      }
    }
  }

  void _createAnimationController(String itemId) {
    final controller = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 300),
    );

    _animControllers[itemId] = controller;

    final item = widget.items.firstWhere((item) => item.id == itemId);
    _updateAnimationsForItem(itemId, item);
  }

  void _updateAnimationsForItem(String itemId, TransformableItem item) {
    final controller = _animControllers[itemId]!;

    _scaleAnimations[itemId] = Tween<double>(
      begin: item.scale,
      end: 1.0,
    ).animate(controller);

    _rotationAnimations[itemId] = Tween<double>(
      begin: item.rotation,
      end: 0.0,
    ).animate(controller);

    // Use absolute offset for animations
    _offsetAnimations[itemId] = Tween<Offset>(
      begin: _relativeToAbsoluteOffset(item.relativeOffset),
      end: Offset.zero,
    ).animate(controller);
  }

  void _resetTransformation(String itemId) {
    final item = widget.items.firstWhere((item) => item.id == itemId);
    _updateAnimationsForItem(itemId, item);

    _animControllers[itemId]!.forward(from: 0.0).whenComplete(() {
      setState(() {
        item.scale = 1.0;
        item.rotation = 0.0;
        item.relativeOffset = Offset.zero;
        _notifyItemTransformUpdate(itemId);
      });
    });
  }

  String? _findItemBetweenTouchPoints(Offset point1, Offset point2) {
    // Calculate the midpoint between the two touch points
    final midpoint = Offset(
      (point1.dx + point2.dx) / 2,
      (point1.dy + point2.dy) / 2,
    );

    // Find which item contains this midpoint
    for (final item in widget.items) {
      // Calculate item's bounds based on its position and transformation
      final absoluteOffset = _relativeToAbsoluteOffset(item.relativeOffset);
      final itemCenter = Offset(
        widget.containerSize.width / 2 + absoluteOffset.dx,
        widget.containerSize.height / 2 + absoluteOffset.dy,
      );

      // Simplified check - just see if midpoint is close to the item center
      final distance = (itemCenter - midpoint).distance;
      if (distance < 100) {
        // Adjust this threshold based on your needs
        return item.id;
      }
    }

    return null;
  }

  @override
  void dispose() {
    for (final controller in _animControllers.values) {
      controller.dispose();
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: widget.containerSize.width,
      height: widget.containerSize.height,
      child: GestureDetector(
        behavior: HitTestBehavior.translucent,
        onScaleStart: !widget.allowRotation &&
                !widget.allowScaling &&
                !widget.allowTranslation
            ? null
            : (details) {
                if (details.pointerCount == 2) {
                  // _focalPointStart = details.focalPoint;

                  final String? itemId = _findItemBetweenTouchPoints(
                    details.localFocalPoint,
                    details
                        .localFocalPoint, // Update this if you can get both points
                  );

                  setState(() {
                    _activeItemId = itemId;
                    _singleFingerItemId = null; // Reset single finger tracking
                  });

                  if (_activeItemId != null) {
                    final item = widget.items
                        .firstWhere((item) => item.id == _activeItemId);
                    _baseScale = item.scale;
                    _baseRotation = item.rotation;
                  }
                } else if (details.pointerCount == 1) {
                  _lastSingleFingerPosition = details.localFocalPoint;
                  final String? itemId =
                      _findItemAtPoint(details.localFocalPoint);

                  if (itemId != null) {
                    setState(() {
                      _singleFingerItemId = itemId;
                      _activeItemId = null; // Reset multi-finger tracking
                    });
                  }
                }
              },
        onScaleEnd: !widget.allowRotation &&
                !widget.allowScaling &&
                !widget.allowTranslation
            ? null
            : (details) {
                if (widget.onTransformEnd != null) {
                  widget.onTransformEnd!(details);
                }
                setState(() {
                  _activeItemId = null;
                  _singleFingerItemId = null;
                });
              },
        onScaleUpdate: !widget.allowRotation &&
                !widget.allowScaling &&
                !widget.allowTranslation
            ? null
            : (details) {
                // Handle two-finger gestures
                if (_activeItemId != null && details.pointerCount == 2) {
                  if (!widget.allowScaling &&
                      !widget.allowRotation &&
                      !widget.allowTranslation) return;

                  final TransformableItem item = widget.items
                      .firstWhere((item) => item.id == _activeItemId);

                  setState(() {
                    // Handle scaling
                    if (widget.allowScaling) {
                      item.scale = (_baseScale * details.scale)
                          .clamp(widget.minScale, widget.maxScale);
                    }

                    // Handle rotation
                    if (widget.allowRotation) {
                      item.rotation = _baseRotation + details.rotation;
                    }

                    // Handle translation - convert delta to relative
                    if (widget.allowTranslation) {
                      final relativeDelta = Offset(
                        details.focalPointDelta.dx / widget.containerSize.width,
                        details.focalPointDelta.dy /
                            widget.containerSize.height,
                      );
                      item.relativeOffset += relativeDelta;
                    }

                    _notifyItemTransformUpdate(_activeItemId!);
                  });
                }
                // Handle one-finger panning
                else if (_singleFingerItemId != null &&
                    details.pointerCount == 1 &&
                    widget.allowTranslation) {
                  final TransformableItem item = widget.items
                      .firstWhere((item) => item.id == _singleFingerItemId);

                  final delta =
                      details.localFocalPoint - _lastSingleFingerPosition;
                  _lastSingleFingerPosition = details.localFocalPoint;

                  setState(() {
                    // Convert absolute delta to relative delta
                    final relativeDelta = Offset(
                      delta.dx / widget.containerSize.width,
                      delta.dy / widget.containerSize.height,
                    );
                    item.relativeOffset += relativeDelta;
                    _notifyItemTransformUpdate(_singleFingerItemId!);
                  });
                }
              },
        onDoubleTapDown: (details) {
          // Find which item was double-tapped
          final tapPosition = details.localPosition;
          String? tappedItemId = _findItemAtPoint(tapPosition);

          if (tappedItemId != null) {
            _resetTransformation(tappedItemId);
          }
        },
        child: Stack(
          children:
              widget.items.map((item) => _buildTransformedItem(item)).toList(),
        ),
      ),
    );
  }

  Widget _buildTransformedItem(TransformableItem item) {
    final isAnimating = _animControllers[item.id]?.isAnimating ?? false;

    return AnimatedBuilder(
      animation: _animControllers[item.id] ?? const AlwaysStoppedAnimation(0),
      builder: (context, child) {
        final scale = isAnimating
            ? _scaleAnimations[item.id]?.value ?? item.scale
            : item.scale;
        final rotation = isAnimating
            ? _rotationAnimations[item.id]?.value ?? item.rotation
            : item.rotation;

        // Handle offset - use absolute offset for positioning
        final Offset absoluteOffset;
        if (isAnimating) {
          absoluteOffset = _offsetAnimations[item.id]?.value ??
              _relativeToAbsoluteOffset(item.relativeOffset);
        } else {
          absoluteOffset = _relativeToAbsoluteOffset(item.relativeOffset);
        }

        return Positioned.fill(
          child: Center(
            child: Transform(
              transform: Matrix4.identity()
                ..translate(absoluteOffset.dx, absoluteOffset.dy)
                ..rotateZ(rotation)
                ..scale(scale),
              alignment: Alignment.center,
              child: item.child,
            ),
          ),
        );
      },
    );
  }

  void _notifyItemTransformUpdate(String itemId) {
    if (widget.onItemTransformUpdated != null) {
      final item = widget.items.firstWhere((item) => item.id == itemId);
      final absoluteOffset = _relativeToAbsoluteOffset(item.relativeOffset);
      widget.onItemTransformUpdated!(itemId, item.scale, item.rotation,
          item.relativeOffset, absoluteOffset);
    }
  }

  // Helper method to find an item at a specific point
  String? _findItemAtPoint(Offset point) {
    // Check items in reverse order (top to bottom in z-index)
    for (int i = widget.items.length - 1; i >= 0; i--) {
      final item = widget.items[i];

      // Calculate item's center position using absolute coordinates
      final absoluteOffset = _relativeToAbsoluteOffset(item.relativeOffset);
      final itemCenter = Offset(
        widget.containerSize.width / 2 + absoluteOffset.dx,
        widget.containerSize.height / 2 + absoluteOffset.dy,
      );

      // Simple distance-based hit testing
      final distance = (itemCenter - point).distance;
      if (distance < 100) {
        // Adjust threshold based on item size
        return item.id;
      }
    }

    return null;
  }
}
